# Generated by Django 5.0.6 on 2024-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('empId', models.CharField(max_length=10)),
                ('empPhone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
